spring.application.name=ida
#spring.profiles.active=local
server.port=8088
debug=true


# To disable spring boot logs
logging.level.org.springframework=OFF
logging.level.root=OFF
spring.main.banner-mode=off
logging.level.et.fayda=DEBUG
ida.encoding.urlsafe=true
spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


fayda.partner.id=mpartner-tech5-lora
fayda.base.url=https://api-internal.oracle1.fayda.et
fayda.env=Staging


clientId=mosip-regproc-client
secretKey=hY98OcJIkskFb2yD
appId=regproc
ida.reference.id=PARTNER
mispLicenseKey= jq8Ta9gRaETEpbBiaOipDDylI0rA5JfhAfirZxFANw2Wj4cQ6n
partnerId=mpartner-tech5-lora
partnerApiKey=630756

partner.p12.certificate=C:\\Users\\amanu\\Desktop\\ida\\keys\\mpartner-tech5-lora-partner.p12
partner.p12.certificate.keyAlias=keyAlias
partner.p12.certificate.keyPassword=qwerty@123
partner.public.key.certificate=C:\\Users\\amanu\\Desktop\\ida\\keys\\mpartner-tech5-lora-partner.cer




ida.otp.url = ${fayda.base.url}/idauthentication/v1/otp/${mispLicenseKey}/${partnerId}/${partnerApiKey}
ida.auth.url=${fayda.base.url}/idauthentication/v1/auth/${mispLicenseKey}/${partnerId}/${partnerApiKey}
ida.ekyc.url=${fayda.base.url}/idauthentication/v1/kyc/${mispLicenseKey}/${partnerId}/${partnerApiKey}
ida.certificate.url = ${fayda.base.url}/idauthentication/v1/internal/getCertificate
ida.authmanager.url=${fayda.base.url}/v1/authmanager/authenticate/clientidsecretkey
ida.internal.jwtSign.url=${fayda.base.url}/idauthentication/v1/internal/jwtSign

#ida.captureRequest.uri=http://127.0.0.1:4501/capture

p12.password=qwerty@123
p12.path=C:\\Users\\amanu\\Desktop\\ida\\keys


ida.ssl.verify=false
