spring.application.name=ida
#spring.profiles.active=local
server.port=8089
debug=false

# Disable Spring Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


# To disable spring boot logs
logging.level.org.springframework=OFF
logging.level.root=OFF
spring.main.banner-mode=off
logging.level.et.fayda=DEBUG
ida.encoding.urlsafe=true


fayda.partner.id=fayda-partner
fayda.base.url=https://test.fayda.et
fayda.env=Staging


clientId=test
secretKey=test
appId=test
ida.reference.id=PARTNER
mispLicenseKey=test
partnerId=fayda-partner
partnerApiKey=630756

partner.p12.certificate=path/to/fayda-partner.p12
partner.p12.certificate.keyAlias=keyAlias
partner.p12.certificate.keyPassword=key-password
partner.public.key.certificate=path/to/fayda-partner.cer




ida.otp.url=${fayda.base.url}/idauthentication/v1/otp/${mispLicenseKey}/${partnerId}/${partnerApiKey}
ida.auth.url=${fayda.base.url}/idauthentication/v1/auth/${mispLicenseKey}/${partnerId}/${partnerApiKey}
ida.ekyc.url=${fayda.base.url}/idauthentication/v1/kyc/${mispLicenseKey}/${partnerId}/${partnerApiKey}
ida.certificate.url=${fayda.base.url}/idauthentication/v1/internal/getCertificate
ida.authmanager.url=${fayda.base.url}/v1/authmanager/authenticate/clientidsecretkey
ida.internal.jwtSign.url=${fayda.base.url}/idauthentication/v1/internal/jwtSign

#ida.captureRequest.uri=http://127.0.0.1:4501/capture

p12.password=key-password
p12.path=path/to/keys


ida.ssl.verify=false
